import { Geist, Geist_Mono, Inter,Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import AddToCart from "../components/addToCart";
import { CartProvider } from '../context/CartContext'; 


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased pl-5 pr-5 pt-5 relative`}
      >
        <CartProvider>
        <Header className='w-[100%] z-100'></Header>
        <div className="absolute right-0">
        <AddToCart></AddToCart>
        </div>
        <div className="fade-in-page layout">
        {children}
        </div>
        <Footer></Footer>
        </CartProvider>

        
      </body>
    </html>
  );
}
